#!/bin/sh
# Xcode Cloud post-clone hook.
#
# `ios/` is gitignored and regenerated by prebuild, so a fresh clone has no
# Xcode project at all. This rebuilds it before Xcode Cloud looks for the
# workspace. Mirrors the local release steps in CLAUDE.md.
set -e

cd "$CI_PRIMARY_REPOSITORY_PATH"

# pnpm 9 specifically: v11 ignores .npmrc's node-linker=hoisted and the bundler
# then fails to resolve babel-preset-expo.
export HOMEBREW_NO_AUTO_UPDATE=1
brew install node@22
export PATH="$(brew --prefix node@22)/bin:$PATH"
npm install -g pnpm@9.7.1

pnpm install --frozen-lockfile

# Generates ios/ (incl. the SkateSpots widget target) and runs pod install.
npx expo prebuild --clean --platform ios

# apple-targets resets the widget's CURRENT_PROJECT_VERSION to 1; App Store
# Connect rejects an extension whose build number differs from the app's.
node scripts/sync-widget-version.js

echo "ci_post_clone: done"
ls -d ios/SkateHive.xcworkspace
